# /* Copyright (C) 2022 Cloud Data Consultants Inc. - All Rights Reserved - 
# *
# * You may not copy, reproduce, distribute, transmit, modify, create derivative works, 
# * or in any other way exploit any part of copyrighted material without permission.
# * 
# */
name: 'cdc_dbt_codegen'
version: '0.1.5'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  cdc_dbt_codegen:
    source_db: ['snowflake']

models:
  cdc_dbt_codegen:
    tmp:
      +materialized: view
    +materialized: table
    +schema: stg_source

seed-paths: ["seeds"]